name: Deploy
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@main
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12.18.0"
      - name: build
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN  }}
          SSH_KEY: ${{ secrets.SSH_KEY  }}
        run: |
          npm install
          npm run sync
          deploy=0
          if [ -n "$(git status -s)" ];then
              git add .
              git config --global user.name "furacas"
              git config --global user.email "ci@yeyu.im"
              git commit -m "update cache"
              git push https://${GITHUB_TOKEN}@github.com/furacas/blog.git -f
              # build blog
              npm run build
              deploy=1
          fi
          echo "deploy=$deploy" >> $GITHUB_ENV
      - name: deploy
        if: ${{ env.deploy == '1' }}
        uses: yrpang/github-actions-hexo@v1.3
        with:
          deploykey: ${{ secrets.SSH_KEY }}
          username: ci-bot
          email: ci@yeyu.im
          if_keep_commit_history: true
          github_page_repository: furacas.github.io
